title: <p align="center"> Shubham Anand </p>
logo: /assets/img/Shubham_Anand_pic.JPG

description:
  <p align="center">
  <a href="www.linkedin.com/in/shubham-anand-aa7560bb">LinkedIn</a> |
  <a href="https://github.com/Shub2204">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & Market Mix Modelling related problems.
  Working in Trinity Life Sciences which is in Healthcare domain for 1 year.
  <br>
  </p>



theme: jekyll-theme-minimal
